/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agency;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SWAPNIL
 */
public class Home extends javax.swing.JFrame {
PreparedStatement pst=null;
Connection con=null;
String sql=null;
ResultSet rs=null;

    /**
     * Creates new form Home
     */
    public Home() {
       
         initComponents();  
           con=JavaConnectDb.ConnectrDb();
           CurrentDate();
       
    }
public void close(){
       WindowEvent  winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

public void CurrentDate(){
Calendar cal=new GregorianCalendar();
int month=cal.get(Calendar.MONTH);
int year=cal.get(Calendar.YEAR);
int day=cal.get(Calendar.DAY_OF_MONTH);
date_txt.setText("Date"+year+"/"+(month+1)+"/"+day);


int second=cal.get(Calendar.SECOND);
int minute=cal.get(Calendar.MINUTE);
int hour=cal.get(Calendar.HOUR);
txt_time.setText("Time"+hour+":"+(minute)+":"+second);



Thread clock;
      clock = new Thread(){
          public void run()
          {
              for(;;){
                  Calendar cal=new GregorianCalendar();
                  int month=cal.get(Calendar.MONTH);
                  int year=cal.get(Calendar.YEAR);
                  int day=cal.get(Calendar.DAY_OF_MONTH);
                  date_txt.setText("Date"+year+"/"+(month+1)+"/"+day);
                  
                  
                  int second=cal.get(Calendar.SECOND);
                  int minute=cal.get(Calendar.MINUTE);
                  int hour=cal.get(Calendar.HOUR);
                  txt_time.setText(hour+":"+(minute)+":"+second);
                  
                  try{
                      Thread.sleep(1000);
                  }
                  catch(InterruptedException e){
                      JOptionPane.showMessageDialog(null,e);
                  }
              }
          }
      };
clock.start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        date_txt = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        u = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 51, 51));
        l1.setText("     WELCOME TO ESTATE AGENCY CENTRE");
        getContentPane().add(l1);
        l1.setBounds(180, 20, 520, 70);

        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agency/500_F_33240296_M5fbqYSbYiDm9B8oooyUYuluADLHJFvV.jpg"))); // NOI18N
        jButton2.setText("To Book a Flat Click Here");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 420, 130, 110);

        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agency/Home-Icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 410, 130, 120);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Client");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 550, 60, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Flats");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 550, 70, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agency/REAL-ESTATE-LOGO.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 90, 250, 230);

        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agency/banner_img_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 780, 450);

        jButton5.setFont(new java.awt.Font("Century", 2, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 153));
        jButton5.setText("SignOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(730, 10, 90, 23);

        date_txt.setText("Date:");
        getContentPane().add(date_txt);
        date_txt.setBounds(290, 0, 180, 40);
        getContentPane().add(txt_time);
        txt_time.setBounds(500, 0, 140, 40);
        getContentPane().add(u);
        u.setBounds(710, 10, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        Clent c=new Clent();
       c.f1.setText(this.u.getText());
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       close();
       aflats af=new aflats();
       
       af.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
               close();
      Login l=new Login();
      l.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel txt_time;
    public javax.swing.JLabel u;
    // End of variables declaration//GEN-END:variables
}
