/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agency;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author SWAPNIL
 */
public class signup extends javax.swing.JFrame {
PreparedStatement pst=null;
Connection con=null;
String sql=null;
String gender;
    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        con=JavaConnectDb.ConnectrDb();
    }
    public void close(){
       WindowEvent  winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        mno = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        dat = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Fname");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(254, 94, 39, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Lname");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(255, 147, 38, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(255, 199, 56, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(255, 254, 54, 17);
        getContentPane().add(fname);
        fname.setBounds(455, 93, 90, 30);
        getContentPane().add(lname);
        lname.setBounds(455, 146, 90, 30);
        getContentPane().add(username);
        username.setBounds(455, 198, 90, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("DOB");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(255, 379, 29, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Mobile No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(255, 430, 64, 17);

        submit.setForeground(new java.awt.Color(0, 153, 51));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(370, 490, 80, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agency/btn-SignUpNow.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 10, 351, 65);
        getContentPane().add(password);
        password.setBounds(455, 251, 90, 30);

        mno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnoActionPerformed(evt);
            }
        });
        mno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnoKeyTyped(evt);
            }
        });
        getContentPane().add(mno);
        mno.setBounds(460, 440, 90, 30);

        b1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(0, 153, 153));
        jRadioButton3.setText("Male");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(420, 310, 60, 23);

        b1.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton4.setText("Female");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(520, 310, 59, 23);

        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("Gender");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(260, 320, 50, 20);

        dat.setDateFormatString("dd-MMM-yy");
        getContentPane().add(dat);
        dat.setBounds(460, 380, 120, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agency/url1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 0, 750, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
          

           try {
  if(mno.getText().length()<10 ||mno.getText().length()>10 ){
       JOptionPane.showMessageDialog(null, "Invalid Mobile number ");
  }
  else{
     
            sql="insert into signup(fname,lname,username,password,dob,mnumber,gender) values (?,?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1,fname.getText());
            pst.setString(2,lname.getText());
            pst.setString(3,username.getText());
            pst.setString(4,password.getText());
            pst.setString(5,((JTextField)dat.getDateEditor().getUiComponent()).getText());
            pst.setString(6,mno.getText());
             pst.setString(7,gender);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Thank You for signin "+(username.getText()));
           Clent c=new Clent();
          
           fname.setText("");
        lname.setText("");
        username.setText("");
        password.setText("");
        dat.setCalendar(null);
        
        mno.setText("");
            close();
            Login l=new Login();
            l.setVisible(true);
           
        }
           }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e); 
       }
        
        
    // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        gender="male";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        gender="female";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void mnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnoKeyTyped
       char c=evt.getKeyChar();
       if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
           getToolkit().beep();
           evt.consume();
       }
           
    }//GEN-LAST:event_mnoKeyTyped

    private void mnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup b1;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mno;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
